// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type EventsInitParameters struct {

	// When true, saved admin events will included detailed information for create/update requests. Defaults to false.
	AdminEventsDetailsEnabled *bool `json:"adminEventsDetailsEnabled,omitempty" tf:"admin_events_details_enabled,omitempty"`

	// When true, admin events are saved to the database, making them available through the admin console. Defaults to false.
	AdminEventsEnabled *bool `json:"adminEventsEnabled,omitempty" tf:"admin_events_enabled,omitempty"`

	// The event types that will be saved to the database. Omitting this field enables all event types. Defaults to [] or all event types.
	EnabledEventTypes []*string `json:"enabledEventTypes,omitempty" tf:"enabled_event_types,omitempty"`

	// When true, events from enabled_event_types are saved to the database, making them available through the admin console. Defaults to false.
	EventsEnabled *bool `json:"eventsEnabled,omitempty" tf:"events_enabled,omitempty"`

	// The amount of time in seconds events will be saved in the database. Defaults to 0 or never.
	EventsExpiration *float64 `json:"eventsExpiration,omitempty" tf:"events_expiration,omitempty"`

	// The event listeners that events should be sent to. Defaults to [] or none. Note that new realms enable the jboss-logging listener by default, and this resource will remove that unless it is specified.
	EventsListeners []*string `json:"eventsListeners,omitempty" tf:"events_listeners,omitempty"`

	// The name of the realm the event settings apply to.
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`
}

type EventsObservation struct {

	// When true, saved admin events will included detailed information for create/update requests. Defaults to false.
	AdminEventsDetailsEnabled *bool `json:"adminEventsDetailsEnabled,omitempty" tf:"admin_events_details_enabled,omitempty"`

	// When true, admin events are saved to the database, making them available through the admin console. Defaults to false.
	AdminEventsEnabled *bool `json:"adminEventsEnabled,omitempty" tf:"admin_events_enabled,omitempty"`

	// The event types that will be saved to the database. Omitting this field enables all event types. Defaults to [] or all event types.
	EnabledEventTypes []*string `json:"enabledEventTypes,omitempty" tf:"enabled_event_types,omitempty"`

	// When true, events from enabled_event_types are saved to the database, making them available through the admin console. Defaults to false.
	EventsEnabled *bool `json:"eventsEnabled,omitempty" tf:"events_enabled,omitempty"`

	// The amount of time in seconds events will be saved in the database. Defaults to 0 or never.
	EventsExpiration *float64 `json:"eventsExpiration,omitempty" tf:"events_expiration,omitempty"`

	// The event listeners that events should be sent to. Defaults to [] or none. Note that new realms enable the jboss-logging listener by default, and this resource will remove that unless it is specified.
	EventsListeners []*string `json:"eventsListeners,omitempty" tf:"events_listeners,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the realm the event settings apply to.
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`
}

type EventsParameters struct {

	// When true, saved admin events will included detailed information for create/update requests. Defaults to false.
	// +kubebuilder:validation:Optional
	AdminEventsDetailsEnabled *bool `json:"adminEventsDetailsEnabled,omitempty" tf:"admin_events_details_enabled,omitempty"`

	// When true, admin events are saved to the database, making them available through the admin console. Defaults to false.
	// +kubebuilder:validation:Optional
	AdminEventsEnabled *bool `json:"adminEventsEnabled,omitempty" tf:"admin_events_enabled,omitempty"`

	// The event types that will be saved to the database. Omitting this field enables all event types. Defaults to [] or all event types.
	// +kubebuilder:validation:Optional
	EnabledEventTypes []*string `json:"enabledEventTypes,omitempty" tf:"enabled_event_types,omitempty"`

	// When true, events from enabled_event_types are saved to the database, making them available through the admin console. Defaults to false.
	// +kubebuilder:validation:Optional
	EventsEnabled *bool `json:"eventsEnabled,omitempty" tf:"events_enabled,omitempty"`

	// The amount of time in seconds events will be saved in the database. Defaults to 0 or never.
	// +kubebuilder:validation:Optional
	EventsExpiration *float64 `json:"eventsExpiration,omitempty" tf:"events_expiration,omitempty"`

	// The event listeners that events should be sent to. Defaults to [] or none. Note that new realms enable the jboss-logging listener by default, and this resource will remove that unless it is specified.
	// +kubebuilder:validation:Optional
	EventsListeners []*string `json:"eventsListeners,omitempty" tf:"events_listeners,omitempty"`

	// The name of the realm the event settings apply to.
	// +kubebuilder:validation:Optional
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`
}

// EventsSpec defines the desired state of Events
type EventsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EventsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EventsInitParameters `json:"initProvider,omitempty"`
}

// EventsStatus defines the observed state of Events.
type EventsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EventsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Events is the Schema for the Eventss API.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,keycloak}
type Events struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.realmId) || (has(self.initProvider) && has(self.initProvider.realmId))",message="spec.forProvider.realmId is a required parameter"
	Spec   EventsSpec   `json:"spec"`
	Status EventsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EventsList contains a list of Eventss
type EventsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Events `json:"items"`
}

// Repository type metadata.
var (
	Events_Kind             = "Events"
	Events_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Events_Kind}.String()
	Events_KindAPIVersion   = Events_Kind + "." + CRDGroupVersion.String()
	Events_GroupVersionKind = CRDGroupVersion.WithKind(Events_Kind)
)

func init() {
	SchemeBuilder.Register(&Events{}, &EventsList{})
}
