// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Events) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *KeystoreAesGenerated) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *KeystoreEcdsaGenerated) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *KeystoreHMACGenerated) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *KeystoreJavaKeystore) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *KeystoreRsa) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *KeystoreRsaGenerated) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserProfile) Hub() {}
