apiVersion: realm.crd.alt/v1alpha1
kind: KeystoreAesGenerated
metadata:
  annotations:
    meta.upbound.io/example-id: realm/v1alpha1/keystoreaesgenerated
  labels:
    testing.upbound.io/example-name: keystore_aes_generated
  name: keystore-aes-generated
spec:
  forProvider:
    active: true
    enabled: true
    name: my-aes-generated-key
    priority: 100
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    secretSize: 16

---

apiVersion: keycloak.crd.alt/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: realm/v1alpha1/keystoreaesgenerated
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    realm: my-realm
