apiVersion: openid.crd.alt/v1alpha1
kind: ClientServiceAccountRealmRole
metadata:
  annotations:
    meta.upbound.io/example-id: openid/v1alpha1/clientserviceaccountrealmrole
  labels:
    testing.upbound.io/example-name: client_service_account_role
  name: client-service-account-role
spec:
  forProvider:
    realmId: ${keycloak_realm.realm.id}
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: realm_role
    serviceAccountUserIdSelector:
      matchLabels:
        testing.upbound.io/example-name: client

---

apiVersion: openid.crd.alt/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openid/v1alpha1/clientserviceaccountrealmrole
  labels:
    testing.upbound.io/example-name: client
  name: client
spec:
  forProvider:
    name: client
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    serviceAccountsEnabled: true

---

apiVersion: keycloak.crd.alt/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: openid/v1alpha1/clientserviceaccountrealmrole
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm

---

apiVersion: keycloak.crd.alt/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: openid/v1alpha1/clientserviceaccountrealmrole
  labels:
    testing.upbound.io/example-name: realm_role
  name: realm-role
spec:
  forProvider:
    name: my-realm-role
    realmId: ${keycloak_realm.realm.id}
