apiVersion: openid.crd.alt/v1alpha1
kind: ClientAuthorizationPermission
metadata:
  annotations:
    meta.upbound.io/example-id: openid/v1alpha1/clientauthorizationpermission
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    name: permission_name
    policies:
    - ${data.keycloak_openid_client_authorization_policy.default.id}
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    resourceServerId: ${keycloak_openid_client.test.resource_server_id}
    resources:
    - ${keycloak_openid_client_authorization_resource.test.id}

---

apiVersion: openid.crd.alt/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openid/v1alpha1/clientauthorizationpermission
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    accessType: CONFIDENTIAL
    authorization:
    - policyEnforcementMode: ENFORCING
    clientId: client_id
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    serviceAccountsEnabled: true

---

apiVersion: keycloak.crd.alt/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: openid/v1alpha1/clientauthorizationpermission
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
