apiVersion: openid.crd.alt/v1alpha1
kind: ClientServiceAccountRole
metadata:
  annotations:
    meta.upbound.io/example-id: openid/v1alpha1/clientserviceaccountrole
  labels:
    testing.upbound.io/example-name: client2_service_account_role
  name: client2-service-account-role
spec:
  forProvider:
    clientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: client1
    realmId: ${keycloak_realm.realm.id}
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: client1_role
    serviceAccountUserIdSelector:
      matchLabels:
        testing.upbound.io/example-name: client2

---

apiVersion: openid.crd.alt/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openid/v1alpha1/clientserviceaccountrole
  labels:
    testing.upbound.io/example-name: client1
  name: client1
spec:
  forProvider:
    name: client1
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: openid.crd.alt/v1alpha1
kind: Client
metadata:
  annotations:
    meta.upbound.io/example-id: openid/v1alpha1/clientserviceaccountrole
  labels:
    testing.upbound.io/example-name: client2
  name: client2
spec:
  forProvider:
    name: client2
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm
    serviceAccountsEnabled: true

---

apiVersion: keycloak.crd.alt/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: openid/v1alpha1/clientserviceaccountrole
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm

---

apiVersion: keycloak.crd.alt/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: openid/v1alpha1/clientserviceaccountrole
  labels:
    testing.upbound.io/example-name: client1_role
  name: client1-role
spec:
  forProvider:
    clientId: ${keycloak_openid_client.client1.id}
    description: A role that client1 provides
    name: my-client1-role
    realmId: ${keycloak_realm.realm.id}
