apiVersion: keycloak.crd.alt/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: keycloak/v1alpha1/user
  labels:
    testing.upbound.io/example-name: user
  name: user
spec:
  forProvider:
    email: bob@domain.com
    enabled: true
    firstName: Bob
    lastName: Bobson
    realmId: ${keycloak_realm.realm.id}
    username: bob

---

apiVersion: keycloak.crd.alt/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: keycloak/v1alpha1/user
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
