// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ClientAuthorizationScopeInitParameters struct {
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	IconURI *string `json:"iconUri,omitempty" tf:"icon_uri,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ClientAuthorizationScopeObservation struct {
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	IconURI *string `json:"iconUri,omitempty" tf:"icon_uri,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`

	ResourceServerID *string `json:"resourceServerId,omitempty" tf:"resource_server_id,omitempty"`
}

type ClientAuthorizationScopeParameters struct {

	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// +kubebuilder:validation:Optional
	IconURI *string `json:"iconUri,omitempty" tf:"icon_uri,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +crossplane:generate:reference:type=github.com/trois-six/provider-keycloak/apis/keycloak/v1alpha1.Realm
	// +kubebuilder:validation:Optional
	RealmID *string `json:"realmId,omitempty" tf:"realm_id,omitempty"`

	// Reference to a Realm in keycloak to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDRef *v1.Reference `json:"realmIdRef,omitempty" tf:"-"`

	// Selector for a Realm in keycloak to populate realmId.
	// +kubebuilder:validation:Optional
	RealmIDSelector *v1.Selector `json:"realmIdSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Required
	ResourceServerID *string `json:"resourceServerId" tf:"resource_server_id,omitempty"`
}

// ClientAuthorizationScopeSpec defines the desired state of ClientAuthorizationScope
type ClientAuthorizationScopeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ClientAuthorizationScopeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClientAuthorizationScopeInitParameters `json:"initProvider,omitempty"`
}

// ClientAuthorizationScopeStatus defines the observed state of ClientAuthorizationScope.
type ClientAuthorizationScopeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClientAuthorizationScopeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ClientAuthorizationScope is the Schema for the ClientAuthorizationScopes API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,keycloak}
type ClientAuthorizationScope struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ClientAuthorizationScopeSpec   `json:"spec"`
	Status ClientAuthorizationScopeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClientAuthorizationScopeList contains a list of ClientAuthorizationScopes
type ClientAuthorizationScopeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClientAuthorizationScope `json:"items"`
}

// Repository type metadata.
var (
	ClientAuthorizationScope_Kind             = "ClientAuthorizationScope"
	ClientAuthorizationScope_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClientAuthorizationScope_Kind}.String()
	ClientAuthorizationScope_KindAPIVersion   = ClientAuthorizationScope_Kind + "." + CRDGroupVersion.String()
	ClientAuthorizationScope_GroupVersionKind = CRDGroupVersion.WithKind(ClientAuthorizationScope_Kind)
)

func init() {
	SchemeBuilder.Register(&ClientAuthorizationScope{}, &ClientAuthorizationScopeList{})
}
