// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Client) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientAggregatePolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientAuthorizationPermission) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientAuthorizationResource) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientAuthorizationScope) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientClientPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientDefaultScopes) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientGroupPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientJsPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientOptionalScopes) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientPermissions) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientRolePolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientScope) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientServiceAccountRealmRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientServiceAccountRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientTimePolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ClientUserPolicy) Hub() {}
