apiVersion: realm.crd.alt/v1alpha1
kind: Events
metadata:
  annotations:
    meta.upbound.io/example-id: realm/v1alpha1/events
  labels:
    testing.upbound.io/example-name: realm_events
  name: realm-events
spec:
  forProvider:
    adminEventsDetailsEnabled: true
    adminEventsEnabled: true
    enabledEventTypes:
    - LOGIN
    - LOGOUT
    eventsEnabled: true
    eventsExpiration: 3600
    eventsListeners:
    - jboss-logging
    realmId: ${keycloak_realm.realm.id}

---

apiVersion: keycloak.crd.alt/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: realm/v1alpha1/events
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
