apiVersion: realm.keycloak.crd.alt/v1alpha1
kind: RealmKeyStoreAESGenerated
metadata:
  annotations:
    meta.upbound.io/example-id: realm/v1alpha1/realmkeystoreaesgenerated
  labels:
    testing.upbound.io/example-name: keystore_aes_generated
  name: keystore-aes-generated
spec:
  forProvider:
    active: true
    enabled: true
    name: my-aes-generated-key
    priority: 100
    realmId: ${keycloak_realm.realm.id}
    secretSize: 16

---

apiVersion: keycloak.keycloak.crd.alt/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: realm/v1alpha1/realmkeystoreaesgenerated
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider: {}
