apiVersion: default.crd.alt/v1alpha1
kind: Groups
metadata:
  annotations:
    meta.upbound.io/example-id: default/v1alpha1/groups
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    groupIds:
    - ${keycloak_group.group.id}

---

apiVersion: keycloak.crd.alt/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: default/v1alpha1/groups
  labels:
    testing.upbound.io/example-name: group
  name: group
spec:
  forProvider:
    name: my-group
    realmIdSelector:
      matchLabels:
        testing.upbound.io/example-name: realm

---

apiVersion: keycloak.crd.alt/v1alpha1
kind: Realm
metadata:
  annotations:
    meta.upbound.io/example-id: default/v1alpha1/groups
  labels:
    testing.upbound.io/example-name: realm
  name: realm
spec:
  forProvider:
    enabled: true
    realm: my-realm
